"""create llm

Revision ID: c7dc31e6f570
Revises: 8a907e39d832
Create Date: 2025-05-26 14:42:33.328571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7dc31e6f570'
down_revision = '8a907e39d832'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_base', sa.String(), nullable=True),
    sa.Column('azure_deployment_model', sa.String(), nullable=True),
    sa.Column('azure_embedding_model', sa.String(), nullable=True),
    sa.Column('open_ai_version', sa.String(), nullable=True),
    sa.Column('open_ai_type', sa.String(), nullable=True),
    sa.Column('model_engine', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.Column('model_token_limit', sa.Integer(), nullable=True),
    sa.Column('output_token_limit', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_id'), 'llm', ['id'], unique=False)
    op.create_table('usersearchindex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_index_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersearchindex_id'), 'usersearchindex', ['id'], unique=False)
    op.drop_index('ix_usercollection_id', table_name='usercollection')
    op.drop_table('usercollection')
    op.add_column('domain', sa.Column('search_index_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'search_index_name')
    op.create_table('usercollection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='usercollection_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usercollection_pkey')
    )
    op.create_index('ix_usercollection_id', 'usercollection', ['id'], unique=False)
    op.drop_index(op.f('ix_usersearchindex_id'), table_name='usersearchindex')
    op.drop_table('usersearchindex')
    op.drop_index(op.f('ix_llm_id'), table_name='llm')
    op.drop_table('llm')
    # ### end Alembic commands ###
